author: Sopra Steria AS
year: 2026
license:
  header: |
    Copyright © 2026 Sopra Steria AS

    This file is part of gheese and is licensed under the GNU General Public License v3.0.
  text: |
    Copyright © 2026 Sopra Steria AS

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, version 3.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program. If not, see <https://www.gnu.org/licenses/>.
